before_script:
  - export BUILD_PREFIX=build${CI_PIPELINE_ID}
  - export COMPOSE_PROJECT_NAME=${BUILD_PREFIX}yii2-db
  - cd tests

stages:
  - test
  - report
  - cleanup

test:
  stage: test
  script:
    - set +e
    - cd tests
    - make up setup
    - docker-compose run -e YII_ENV=test --rm phpfpm codecept run --html=_report.html; TESTS_EXIT_CODE=$?
    - set -e
    - mv _output /tmp/${BUILD_PREFIX}
    - exit $TESTS_EXIT_CODE

report:
  stage: report
  script:
    - mv /tmp/${BUILD_PREFIX} _output
  artifacts:
    paths:
      - tests/_output/
  when: always

cleanup:
  stage: cleanup
  script:
    - docker-compose kill && docker-compose rm -fv
    - docker-compose down --rmi local --volumes
  when: always

